templates/common/app/404.html

In other files we use a lowercased doctype: https://github.com/yeoman/generator-angular/blob/8416c549a24eb30cd7f9763682d81bb8718c1681/templates/common/app/index.html#L1, so this was kinda inconsistent.

404.html: use lowercase doctype

---

templates/common/root/_Gruntfile.js

Unless we remove all css related tasks from 'test' task as I don't think current build can test css

fix(karma): compass and autoprefixer need wiredep:sass for test task

---

CHANGELOG.md

Most relative links at
https://github.com/yeoman/generator-angular/blob/master/CHANGELOG.md
leads to github 404.

fix(docs): replace relative links with absolute in changelog

---

script-base.js
templates/common/root/_bower.json

app-suffix option is not saved for later uses and needs to be readded to each
future subgenerator. This change reads module name from new bower.json field
so module author have full flexibility about naming it.

feat(app): read module name form bower.json

---

templates/common/app/index.html

We dropped support for IE8.
Ref https://github.com/yeoman/generator-angular/commit/7c6f245b73ce59782aed0a1efd300e83569eb0e8

fix(app): update `browsehappy` conditional comment

---

templates/common/app/index.html

We don't have Modernizr, so this class should not be there. It never switches to `js`.

fix(app): remove `no-js` class

---

readme.md

`grunt-cli` should be installed global and `grunt` not
Info: https://github.com/yeoman/yo/commit/65a65757c007d0ad926020dfb1ace53b12bdf635

docs(docs): change grunt to grunt-cli

---

templates/common/app/robots.txt

The robots.txt standard:
> " The record starts with one or more User-agent lines, followed by one or
more Disallow lines, as detailed below. "
Ref https://github.com/yeoman/generator-gulp-webapp/pull/220
https://github.com/h5bp/html5-boilerplate/issues/1487
http://www.robotstxt.org/orig.html

fix(app): Add `Disallow:` to robots.txt

---

templates/common/app/404.html

Our current browser support does not require the usage of these hacks anymore.
Ref https://github.com/yeoman/generator-angular/commit/7c6f245b73ce59782aed0a1efd300e83569eb0e8

fix(app): remove IE6/7 CSS hacks

---

templates/common/root/_Gruntfile.js

Fixes https://github.com/yeoman/generator-angular/commit/b7b72b00330ba09594f148c3a87d047c69a1a15e

fix(ngtemplates): should build templateCache.js into .tmp

---

templates/common/root/gitignore

The generated .gitignore contains relative paths that will match
in both the root of the project or somewhere down the tree.
This can be problematic if the project gets a folder called `dist`
or some other ignored name.
This patch makes the default .gitignores absolute.

fix(gen): use absolute paths in generated .gitignore

---

route/index.js

I think like the predefined `MainCtrl` the name in the `controllerAs` property should not forced to start with a capital.
https://github.com/yeoman/generator-angular/blob/master/templates/javascript/app.js#L18

fix(gen): switch ctrlAs name to a cameledName

---

app/index.js

option() method doesn't accept a 'required' config parameter.

fix(app): remove invalid parameter in app-suffix option config

---

templates/common/root/_package.json

Fix Issue #1099
Fixes failing tests by ensuring that Base.prototype.rootGeneratorName can find a name when used with package.json in the generated output.

Add a "name" field to _package.json package.

---

templates/common/root/_package.json

Fix Issue #1101 - having a space in a package name is invalid. The tests don't catch this but the generated package.json is invalid during use :-(

Use lowercase package name without spaces

---

provider/index.js
templates/coffeescript/spec/provider.coffee
templates/javascript/spec/provider.js

WIP. A separate template for testing providers. Allows users to start quicker testing providers without searching the way to access serviceProvider from test file.

feat(templates): add provider test scafolding

---

templates/common/root/_Gruntfile.js

Enabling HTML minifier's `removeOptionalTags` option alongside libraries like the [AngularUI Router](https://github.com/angular-ui/ui-router#angularui-router-) causes iOS 8 devices to throw an ```TypeError: Attempted to assign to readonly property``` error. See screenshot [here](http://i.imgur.com/ID1Ynwt.jpg).
This obscure iOS8 ```TypeError` is a [known issue](https://github.com/angular/angular.js/issues/9128) in AngularJS, but on some cases, the fix is just to [disable removeOptionalTags](https://github.com/angular/angular.js/issues/9128#issuecomment-111648953) from `htmlmin`. As such, it shouldn't be enabled by default here.

fix(htmlmin): disable the removeOptionalTags option.

---

templates/common/root/_Gruntfile.js

sourcemap doesn't update when SASS file changes because of autoprefixer:dist task running. Only autoprefixer:server task should run

fix(watch): sourcemap not updated on sass file change

---

templates/coffeescript/spec/controller.coffee
templates/javascript/spec/controller.js

Creating new $scope for controller tests both is good practice and
prevents the grunt task failing on a clean install due to jshint
warnings.
Closes #1130

fix(app): create new $scope for controller tests

---

common/index.js
templates/common/root/.jscsrc
templates/common/root/_Gruntfile.js
templates/common/root/_package.json
test/test-apppath.js
test/test-file-creation.js

Added jscs to replace styling rules deprecated by jshint. Details
can be found here regarding the rules that were previously used
by this generator: https://github.com/yeoman/generator-angular/pull/1086
Jscs rule descriptions can be found here: http://jscs.info/rules.html
Closes #1109

feat(gen): add jscs

---

templates/common/root/_Gruntfile.js
templates/common/root/_package.json

Upgrading grunt-autoprefixer to grunt-postcss to remove deprecation warnings.
Added new npm package with post-css dependencies and removed deprecated grunt-autoprefixer. Fixes #1132

Upgrading autoprefixer to postcss. Fixes #1132

---

app/index.js
templates/common/root/_Gulpfile.js
templates/common/root/_package.json

I solved the merge conflicts of pending pull request https://github.com/yeoman/generator-angular/pull/672 and meanwhile updated some gulp dependencies (clean -> rimraf, ngmin -> ngAnnotate) and adjusted the code to the changed file structure.

Finishing experimental Gulp implementation

---

templates/common/root/_package.json

Make sure the comma is placed correctly when selecting gulp.

fix(pkg): comma

---

templates/common/root/_gulpfile.js
templates/common/root/_package.json

Upgrading the gulp-useref plugin to version 3.0.
3.0 has a simpler API. It only uses one stream now for html and assets so it simplifies the gulp task quite a bit.

Upgrade gulp-useref version and gulp task to 3.0.

---

templates/common/root/_package.json

A fix to #1224 .
I came across this issue in importing `lodash.d.ts`. A new syntax of intersection type was introduced in typescript 1.6, and is used in latest lodash's definition file, but compiling it with current grunt-typescript (0.6.2) will throw a error.

chore(deps): Update grunt-typescript to v0.8.0

---

readme.md

Delete comparison link which is not directly functional and replace with link to a list that contains optional generators.

create link to list of generators at Yeoman.io in readme

---

templates/common/root/_package.json

grunt-contrib-cssmin <1.0.2 issue with node v6: [link](https://github.com/gruntjs/grunt-contrib-cssmin/pull/271/commits/11e655873dfa58b6edcda0113cee612f7a6b2ab9?diff=split) 
Fixes: #1320

fix(deps): update grunt-contrib-cssmin to 1.0.2

---

templates/javascript/app.js

Starting with Angular v.1.6.0, the default hash-prefix used for $location hash-bang URLs has changed from the empty string ('') to the bang ('!').
This means that the links from an app created with "yo angular" won't work, since Angular ^1.4.0 will resolve to angular 1.6.0 or newer.
I believe most people prefer to keep the # symbol instead of #!
Closes #1380

fix(url contain '%2F' instead of '/')
